# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('description', models.CharField(default='No Description', max_length=1000)),
                ('status', models.CharField(choices=[('C', 'Complete'), ('I', 'In Progress'), ('W', 'Waiting')], default='W', max_length=1)),
                ('priority', models.IntegerField(default=5)),
                ('submissionDate', models.DateTimeField(verbose_name='date submitted')),
            ],
        ),
    ]
